# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Quilt Shop Proximity lets you know when you are close to a quilt shop."
REPO_LICENSE=""
REPO_TOPICS="godot-application,ios-app,quilting"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/quilt-shop-proximity.git"
REPO_WEB_URL="https://github.com/fini-net/quilt-shop-proximity"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="quilt-shop-proximity"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "godot-application"
    "ios-app"
    "quilting"
)
